Importing dependencies

In [89]:
import pandas as pd
import numpy as np

Data preprocessing

In [90]:
my_path = "/content/sample_data/spam_dataset.csv"
df = pd.read_csv(my_path)
df.head(10)

                                     message_content  is_spam
0  Hello Lonnie,\n\nJust wanted to touch base reg...        0
1  Congratulations, you've won a prize! Call us n...        1
2  You have been pre-approved for a credit card w...        1
3  Limited time offer, act now! Only a few spots ...        1
4  Your loan has been approved! Transfer funds to...        1
5  You have been selected to receive a special of...        1
6  Hello Christian,\n\nJust wanted to touch base ...        0
7  Dear Bethany,\n\nI hope you’re doing well. I j...        0
8  Free vacation, no strings attached! Book now a...        1
9  Claim your free gift now! Limited time offer.\...        1

Check the size of our data

In [91]:
print(f"Number of records is: {df.shape[0]}")
print(f"Number of field is: {df.shape[1]}")

Number of records is: 1000
Number of field is: 2

Getting a picture of how out data is like, nulls, datatype,features

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   message_content  1000 non-null   object
 1   is_spam          1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

Check the data after renaming feature

In [93]:
df=df.rename(columns={'is_spam':'label'})
df.head()

                                     message_content  label
0  Hello Lonnie,\n\nJust wanted to touch base reg...      0
1  Congratulations, you've won a prize! Call us n...      1
2  You have been pre-approved for a credit card w...      1
3  Limited time offer, act now! Only a few spots ...      1
4  Your loan has been approved! Transfer funds to...      1

Assigning variables

In [94]:
x = df['message_content']
y = df['label']

In [95]:
from sklearn.model_selection import train_test_split

Splitting the data

In [96]:
X_train, X_test, Y_train, Y_test =train_test_split(x,y, test_size=0.2, random_state=42)

Check the size of train and test data

In [97]:
print (f"Size of train data is: {X_train.shape}")
print (f"Size of test data is: {X_test.shape}")

Size of train data is: (800,)
Size of test data is: (200,)

Transform text data to feature vector that can be used as input to the model

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [99]:
feature_extraction=TfidfVectorizer(min_df=1, stop_words='english',lowercase=True)
X_train_tfidf =feature_extraction.fit_transform(X_train)
X_test_tfidf = feature_extraction.transform(X_test)

import logistic regression model

In [101]:
from sklearn.linear_model import LogisticRegression

Train model

In [102]:
model = LogisticRegression()
model.fit(X_train_tfidf, Y_train)

LogisticRegression()

import evaluation metrics

In [103]:
from sklearn.metrics import accuracy_score, f1_score

Prediction on train data

In [104]:
Y_pred = model.predict(X_train_tfidf)

accuracy_on_train_data = accuracy_score(Y_pred, Y_train)
f1_score_trained_data = f1_score(Y_pred, Y_train)

In [105]:
print (accuracy_on_train_data)
print (f1_score_trained_data)

1.0
1.0

Prediction on test data

In [106]:
Y_pred = model.predict(X_test_tfidf)

accuracy_on_test_data = accuracy_score(Y_pred, Y_test)
f1_score_test_data = f1_score(Y_pred, Y_test)
print (accuracy_on_test_data)
print (f1_score_test_data)

1.0
1.0

Building predictive system

In [107]:
input_data=["Hello, how are you doing today?",    "Meeting tomorrow at 3pm in conference room"]
input_data_tfidf = feature_extraction.transform(input_data)

In [108]:

prediction = model.predict (input_data_tfidf)

if prediction[0]==1:
  print("Message is a spam")

else:
  print("Not a spam")

Not a spam

In [110]:
import pickle
pickle.dump (model, open('Model.pkl','wb'))